version: "3.8"

services:
  myollama:
    container_name: ollama
    build:
      context: docker-ollama  # The build context (directory containing Dockerfile)
      dockerfile: Dockerfile_ollama  # Name of the Dockerfile (default is "Dockerfile")
    image: ollama/ollama:latest  # Optional: Image name to tag the built image with
    volumes:
      - ./data/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=host.docker.internal
    # environment:
    #   - OLLAMA_ORIGINS=* # Allow all origins
    expose:
      - 11434/tcp
    ports:
      - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    networks:
      - ollama-network
  
  chatapp:
    container_name: chatapp
    build:
      context: docker-python-chatbot  # The build context (directory containing Dockerfile)
      dockerfile: Dockerfile_python_chatbot  # Name of the Dockerfile (default is "Dockerfile")
    image: python:3.9  # Optional: Image name to tag the built image with
    ports:
      - "8000:8000" 
    depends_on:
      - myollama
    # environment:
    #   - OLLAMA_BASE_URL=http://localhost:11434 
    networks:
      - ollama-network
    volumes:
      - .:/app_volume

# Docker Volumes
volumes:
  ollama:

# Docker Networks
networks:
  ollama-network:
    driver: bridge