FROM python:3.9

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y lsof

COPY . .

EXPOSE 8000
#CMD ["python", "app.py"]
CMD ["chainlit", "run", "app.py", "--host", "0.0.0.0", "--port", "8000"] 